import matplotlib.pyplot as plt
import numpy as np
from csnlp.wrappers.mpc.pwa_mpc import PwaMpc
from gymnasium import Env

from slpwampc.core.classifiers.classifier import PartitionClassifier
from slpwampc.core.systems import PwaSystem
from slpwampc.misc.action_mapping import PwaActionMapper
from slpwampc.misc.regions import Polytope


class Agent:
    """An agent who trains a policy, one for each PWA region, that select
    the switching sequences of a PWA system, in a supervised manner."""

    def __init__(
        self,
        system: PwaSystem,
        time_varying_affine_mpc: PwaMpc,
        classifiers: list[PartitionClassifier],
    ) -> None:
        """Initialize the agent.

        Parameters
        ----------
        system : PwaSystem
            The PWA system.
        time_varying_affine_mpc : PwaMpc
            The agents mpc controller, that uses the switching sequence
            generated by the policy to fix a sequence of pwa regions,
            such that the optimization problem is linear.
        classifiers : list[PartitionClassifier]
            Classifiers that partition each region of the PWA system.
        """
        self.N = time_varying_affine_mpc.prediction_horizon
        self.nx = system.A[0].shape[0]
        self.nu = system.B[0].shape[1]
        self.nr = len(system.A)
        self.action_mapper = PwaActionMapper(len(system.A), self.N)
        self.system = system
        self.time_varying_affine_mpc = time_varying_affine_mpc
        self.classifiers = classifiers

    def get_switching_sequence(self, x: np.ndarray) -> np.ndarray | None:
        """Get the switching sequence for a given state.

        Parameters
        ----------
        x : np.ndarray
            The state.

        Returns
        -------
        np.ndarray | None
            The switching sequence or none if out of feasible set (if feasible set was learned).
        """
        region = self.system.get_region(x)
        pred = self.classifiers[region].predict(x)
        if pred == -1:
            return None
        else:
            return self.action_mapper.get_action_from_label(pred)

    def evaluate(
        self,
        env: Env,
        num_episodes: int,
        seed: int = 0,
        mixed_integer_mpc: PwaMpc | None = None,
        K_term: np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray, list[np.ndarray]]:
        """Evaluate the policy in the environment. If a mixed-integer mpc is provided,
        the learned policy is not used for selecting the switching sequences, as they
        are instead optimized within the MPC. Additionally, a terminal controller can be
        provided to guarentee recursive feasibility, where the sequence is shifted using
        the terminal controller if the policy returns the infeasible flag (-1). Note that
        this has only been implemented for terminal regions that are within one PWA region.

        Parameters
        ----------
        env : Env
            The environment.
        num_episodes : int
            The number of episodes.
        seed : int, optional
            The seed for reseting environment, by default 0.
        mixed_integer_mpc : PwaMpc, optional
            An optional mixed-integer mpc, used to optimize the switchign sequences
            if provided, by default None.
        K_term : np.ndarray, optional
            An optional terminal controller, used to guarentee recursive feasibility.
            If the policy returns a the infeasible flag (-1) and no terminal controller
            is provided, an error is raised, by default None.

        Returns
        -------
        tuple[np.ndarray, np.ndarray, list[np.ndarray]]
            The costs, initial states, and solve times for each episode.

        Raises
        ------
        ValueError
            If the policy indicates infeasibility and no terminal controller is provided,
            if initial state is infeasible for policy, or if any MPC problem is infeasible.
        """
        costs = np.zeros(num_episodes)
        states = np.zeros((num_episodes, self.nx))
        times: list[np.ndarray] = []
        for i in range(num_episodes):
            print(f"Episode {i}/{num_episodes}")
            x, _ = env.reset(seed=seed + i)
            previous_seq = None
            states[i] = x.squeeze()
            truncated, terminated, timestep = False, False, 0
            solve_times: list[float] = []
            while not truncated and not terminated:
                print(f"timestep {timestep}")
                if mixed_integer_mpc is None:
                    seq = self.get_switching_sequence(x)
                    if seq is None:
                        if previous_seq is None:
                            raise ValueError(
                                "Sequence returned for initial state not feasible."
                            )
                        else:
                            if K_term is None:
                                raise ValueError("Terminal controller not provided.")
                            x_N = sol.vals["x"][
                                :, -1
                            ]  # terminal state from previous iteration
                            _, shifted_region = self.system.next_state(
                                x_N, K_term @ x_N
                            )
                            seq = np.vstack((previous_seq[1:], shifted_region))
                    self.time_varying_affine_mpc.set_sequence(seq.flatten().tolist())
                    sol = self.time_varying_affine_mpc.solve({"x_0": x})
                    previous_seq = seq
                else:
                    sol = mixed_integer_mpc.solve({"x_0": x})
                if not sol.success:
                    raise ValueError("Infeasible problem encountered.")

                if "t_wall_total" in sol.stats:
                    solve_times.append(sol.stats["t_wall_total"])
                else:
                    solve_times.append(0.0)

                x, r, truncated, terminated, _ = env.step(
                    (sol.vals["u"][:, 0]).toarray()
                )
                costs[i] += r
                timestep += 1
            times.append(np.array(solve_times))
        return costs, states, times

    def train(
        self,
        initial_state_sets: list[np.ndarray],
        mixed_integer_mpc: PwaMpc,
        learn_infeasible_regions: bool = False,
        tightened_mpc: PwaMpc | None = None,
        plot: bool = False,
        interactive: bool = False,
    ) -> tuple[np.ndarray, np.ndarray, dict]:
        """Train the agent's policy using supervised learning, with optimal sequences
        generated by the mixed-integer mpc.

        Parameters
        ----------
        initial_state_sets : np.ndarray
            The initial state set for training in each PWA region.
        mixed_integer_mpc : PwaMpc
            The mixed-integer mpc used to generate the optimal sequences.
        learn_infeasible_regions : bool, optional
            If true, the agent will learn to classify infeasible regions with label -1.
            If this is false, it should be known a-priori that the MPC problem is
            feasible over the entire state-space.
        tightened_mpc : PwaMpc, optional
            A tightened mpc, required for checking infeasiblity of points on the
            boundary of the feasible set, by default None.
        plot : bool, optional
            If true the training is plotted. By default False.
        interactive : bool, optional
            If true the training is plotted interactively. By default False.

        Returns
        -------
        tuple[np.ndarray, np.ndarray, dict]
            The training data that generates the policy and an info dict."""
        if learn_infeasible_regions and tightened_mpc is None:
            raise ValueError("Tightened mpc required for learning infeasible regions.")
        self.tightened_mpc = (
            tightened_mpc if tightened_mpc is not None else mixed_integer_mpc
        )

        if self.nr != len(initial_state_sets):
            raise ValueError(
                "Number of initial state sets does not match number of regions."
            )

        # instantiate plotting
        if plot and self.nx > 3:
            raise ValueError("Plotting only supported for 2D and 3D.")
        if plot and interactive:
            if self.nx == 2:
                self.fig, self.ax = plt.subplots()
            elif self.nx == 3:
                self.fig = plt.figure()
                self.ax = self.fig.add_subplot(111, projection="3d")
            self.ax.set_axis_off()
            plt.ioff()

        state_train_sets = [np.empty((0, self.nx)) for _ in range(self.nr)]
        action_train_sets = [np.empty((0, 1)) for _ in range(self.nr)]

        state_sets = initial_state_sets
        iter = 0
        finished_regions: list[int] = []
        while True:
            if plot and not interactive:
                if self.nx == 2:
                    self.fig, self.ax = plt.subplots()
                else:
                    self.fig = plt.figure()
                    self.ax = self.fig.add_subplot(111, projection="3d")
            print(
                f"Training iteration {iter}. {sum(state_sets[i].shape[0] for i in range(self.nr))} new states."
            )
            num_regions = 0
            num_infeasible_vertices = 0
            all_regions = []
            for i in finished_regions:  # TODO make this not every iteration
                regions_ = self.classifiers[i].get_partition()
                all_regions.extend(regions_)
                num_regions += len(regions_)
            for i in [
                j for j in range(self.nr) if j not in finished_regions
            ]:  # TODO make in parallel???
                optimal_states, optimal_actions = (
                    self.generate_supervised_learning_data(
                        state_sets[i],
                        mixed_integer_mpc=mixed_integer_mpc,
                        label_infeasible_regions=learn_infeasible_regions,
                        first_region=i,
                    )
                )
                state_train_sets[i] = np.vstack((state_train_sets[i], optimal_states))
                action_train_sets[i] = np.vstack(
                    (action_train_sets[i], optimal_actions)
                )
                print(
                    f"Fitting classifier {i} with {state_train_sets[i].shape[0]} samples."
                )

                self.classifiers[i].fit(
                    state_train_sets[i],
                    action_train_sets[i].ravel(),
                )

                regions: list[Polytope] = self.classifiers[i].get_partition()
                all_regions.extend(regions)

                for region in regions:  # TODO remove this check
                    if not region.is_empty:
                        x = region.get_point()
                        label = self.classifiers[i].predict(x)
                        if label != region.label:
                            raise ValueError("Region label does not match prediction.")

                infeas_vertices = np.empty((0, self.nx, 1))
                all_vertices = np.empty((0, self.nx))
                for region in regions:
                    if not region.is_empty:
                        num_regions += 1
                        vertices = region.V
                        label = region.label
                        all_vertices = np.vstack((all_vertices, vertices))

                        if learn_infeasible_regions and label == -1:
                            for vertex in vertices:
                                sol = self.tightened_mpc.solve(
                                    {"x_0": vertex.reshape(-1, 1)}
                                )
                                if sol.success:
                                    infeas_vertices_ = self.add_circle_points(
                                        vertex.reshape(1, -1, 1),
                                        0.1,
                                        0,
                                        np.vstack((self.system.D, self.system.S[i])),
                                        np.vstack((self.system.E, self.system.T[i])),
                                    )
                                    infeas_vertices = np.vstack(
                                        (infeas_vertices, infeas_vertices_)
                                    )
                        else:
                            # action mapper returns tensor that is vectorizable. Hence we need to convert it to numpy array and remove extra dims
                            switching_sequence = np.asarray(
                                self.action_mapper.get_action_from_label(
                                    np.asarray(label).reshape(1, 1)
                                )
                            ).reshape(-1, 1)

                            for vertex in vertices:
                                self.time_varying_affine_mpc.set_sequence(
                                    switching_sequence.flatten().tolist()
                                )
                                sol = self.time_varying_affine_mpc.solve(
                                    {"x_0": vertex.reshape(-1, 1)}
                                )
                                if not sol.success:
                                    infeas_vertices_ = self.add_circle_points(
                                        vertex.reshape(1, -1, 1),
                                        0.1,
                                        0,
                                        np.vstack((self.system.D, self.system.S[i])),
                                        np.vstack((self.system.E, self.system.T[i])),
                                    )
                                    infeas_vertices = np.vstack(
                                        (infeas_vertices, infeas_vertices_)
                                    )

                # remove duplicates
                all_vertices = np.array(list(set(map(tuple, all_vertices))))
                if infeas_vertices.shape[0] > 0:
                    infeas_vertices = np.array(
                        list(set(map(tuple, infeas_vertices.squeeze(-1))))
                    )[:, :, None]
                    if not self.check_new_points(state_sets[i], infeas_vertices):
                        infeas_vertices = self.add_circle_points(
                            infeas_vertices,
                            0.01,
                            10,
                            np.vstack((self.system.D, self.system.S[i])),
                            np.vstack((self.system.E, self.system.T[i])),
                        )
                else:
                    finished_regions.append(i)
                percentage_infeas = (
                    infeas_vertices.shape[0] / all_vertices.shape[0] * 100
                )
                print(f"Number of vertices: {all_vertices.shape[0]}")
                num_infeasible_vertices += infeas_vertices.shape[0]
                print(f"Number of infeasible vertices: {infeas_vertices.shape[0]}")
                print(f"Percentage of vertices infeas: {percentage_infeas}%")
                state_sets[i] = infeas_vertices

            if plot:
                self.plot_iteration(
                    iter,
                    self.nx == 2,
                    interactive,
                    all_regions,
                    np.concatenate(state_train_sets),
                    np.concatenate(state_sets),
                    np.unique(np.concatenate(action_train_sets)),
                )

            if num_infeasible_vertices == 0:
                if plot:
                    plt.pause(1e5)
                    plt.ioff()
                return (
                    np.concatenate(state_train_sets),
                    np.concatenate(action_train_sets),
                    {"iters": iter, "num_regions": num_regions},
                )
            iter += 1

    def generate_supervised_learning_data(
        self,
        x: np.ndarray,
        mixed_integer_mpc: PwaMpc,
        label_infeasible_regions: bool = False,
        first_region: int | None = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """For a given set of states, generate optimal switching sequences.

        Parameters
        ----------
        x : np.ndarray
            The states. Shape (num_states, nx, 1)
        mixed_integer_mpc : PwaMpc
            The mixed-integer mpc used to generate the optimal sequences.
        label_infeasible_regions : bool, optional
            If true, infeasible points will be labeled with a -1. Otherwise,
            they will be excluded from the training set. By default False.
        first_region : int, optional
            If a first region is passed, the first element of the sequence
            generated by the mpc is set artificially to this region. This
            is to handle the points on the boundary which can have multiple
            optimal first regions. By default None.

        Returns
        -------
        tuple[np.ndarray, np.ndarray]
            The states and the optimal switching sequences."""
        valid_states: list[np.ndarray] = []
        valid_actions: list[int] = []
        for idx, state in enumerate(x):
            # print(f"evaluating optimal action for state {idx} of {x.shape[0]}")
            if label_infeasible_regions:
                valid_states.append(state)
            optimal_action = self.get_switching_sequence_from_mpc(
                state, mixed_integer_mpc
            )
            if optimal_action is not None:
                if not label_infeasible_regions:
                    valid_states.append(state)
                if first_region is not None:
                    optimal_action[0] = first_region
                valid_actions.append(
                    self.action_mapper.get_label_from_action(optimal_action)
                )
            elif label_infeasible_regions:
                valid_actions.append(-1)
        # map the lists to numpy arrays
        optimal_states = np.asarray(valid_states).reshape(-1, self.nx)
        optimal_actions = np.asarray(valid_actions).reshape(-1, 1)
        return optimal_states, optimal_actions

    def get_switching_sequence_from_mpc(
        self, x: np.ndarray, mixed_integer_mpc: PwaMpc
    ) -> np.ndarray | None:
        """Get the switching sequence from a given state by solving the MPC problem.

        Parameters
        ----------
        x : np.ndarray
            The state.
        mixed_integer_mpc : PwaMpc
            The mixed-integer mpc used to generate the optimal sequence.

        Returns
        -------
        np.ndarray | None
            The switching sequence if the problem is feasible, otherwise None."""
        switching_sequence = np.zeros((self.N, 1))
        sol = mixed_integer_mpc.solve({"x_0": x})
        if sol.success:
            delta = sol.vals["delta"]  # binary vars that represent PWA regions
            switching_sequence = np.argmax(delta, axis=0).reshape(-1, 1)
            return switching_sequence
        else:
            return None

    def get_regions(self) -> list[Polytope]:
        """Get the regions of the policy.

        Returns
        -------
        list[Polytope]
            The regions."""
        regions = []
        for i in range(self.nr):
            regions.extend(self.classifiers[i].get_partition())
        return regions

    def plot_iteration(
        self,
        iter: int,
        is_2D: bool,
        interactive: bool,
        regions: list[Polytope],
        state_train_set: np.ndarray,
        infeas_vertices: np.ndarray,
        unique_labels: np.ndarray,
    ) -> None:
        """Plot the current iteration of the training. This plots the current partition, the training data, and the infeasible vertices.

        Parameters
        ----------
        iter : int
            The current iteration.
        is_2D : bool
            If true the plot is 2D, otherwise 3D.
        interactive : bool
            If true the plot is interactive and the axis updates dynamically. Otherwise the figures are blocking.
        regions : list[Polytope]
            The regions of the current SVM policy.
        state_train_set : np.ndarray
            The training data.
        infeas_vertices : np.ndarray
            The current infeasible vertices.
        unique_labels : np.ndarray
            The unique labels."""
        if interactive:
            self.ax.clear()

        self.ax.set_xlim(-12, 12)
        self.ax.set_ylim(-12, 12)
        self.ax.set_axis_off()

        for i, label in enumerate(unique_labels):
            # self.ax.set_title(f"label: {label}")
            for region in [r for r in regions if not r.is_empty and r.label == label]:
                if not region.is_empty:
                    region.plot(
                        ax=self.ax,
                        color=f"C{int(region.label)}" if region.label >= 0 else "black",
                        alpha=0.5,
                    )
            # plt.pause(1)

        if is_2D:
            self.ax.plot(
                state_train_set[:, 0],
                state_train_set[:, 1],
                color="blue",
                marker="o",
                markersize=2,
                linestyle="None",
            )
            self.ax.plot(
                infeas_vertices[:, 0],
                infeas_vertices[:, 1],
                color="red",
                marker="x",
                markersize=5,
                linestyle="None",
            )
            plt.xlim(-12, 12)
            plt.ylim(-12, 12)
        else:
            self.ax.scatter(
                state_train_set[:, 0],
                state_train_set[:, 1],
                state_train_set[:, 2],
                color="blue",
                marker="o",
                s=2,
            )
            self.ax.scatter(
                infeas_vertices[:, 0],
                infeas_vertices[:, 1],
                infeas_vertices[:, 2],
                color="red",
                marker="x",
                s=5,
            )
            self.ax.set_zlim(-12, 12)

        # fig, ax = plt.subplots()
        # ax.set_xlim(-21, 21)
        # ax.set_ylim(-21, 21)
        # self.parc.plot_partition([-15, -15], [15, 15])
        # plt.show()

        # save2tikz(plt.gcf(), name=f"parc_{iter}")
        if not interactive:
            plt.show()
        else:
            self.fig.canvas.draw()
            # plt.savefig(f"iter_{iter}.png")
            plt.pause(0.01)

    def add_circle_points(
        self,
        points: np.ndarray,
        radius: float,
        num_circle_points: int,
        A: np.ndarray,
        b: np.ndarray,
    ) -> np.ndarray:
        """Add points on a circle around the origin to the given points, with points outside the
        region Ax <= b removed.

        Parameters
        ----------
        points : np.ndarray
            The points.
        radius : float
            The radius of the circle.
        num_circle_points : int
            The number of points on the circle.
        A : np.ndarray
            The matrix A in the inequality Ax <= b.
        b : np.ndarray
            The vector b in the inequality Ax <= b.

        Returns
        -------
        np.ndarray
            The points with the added circle points."""
        n, nx, _ = points.shape
        assert nx == 2, "Points must be 2-dimensional for creating a circle."
        angles = np.linspace(0, 2 * np.pi, num_circle_points, endpoint=False)
        circle_points = (
            np.stack((np.cos(angles), np.sin(angles)), axis=1) * radius
        )  # (num_circle_points, 2)
        circle_points = np.repeat(circle_points, n, axis=0).reshape(
            num_circle_points, n, nx, 1
        )
        new_points = (points + circle_points).reshape(-1, nx, 1)
        new_points = new_points[
            np.all(new_points[:, :, 0] @ A.T <= b.squeeze(), axis=1)
        ]
        return np.concatenate((new_points, points), axis=0)

    def check_new_points(self, X: np.ndarray, Y: np.ndarray, eps: float = 0.01) -> bool:
        """Checks if at least one point in Y is not in X, with equality measured with toleramnce
        eps.

        Parameters
        ----------
        X : np.ndarray
            The first set of points, shape = (N, nx).
        Y : np.ndarray
            The second set of points, that are checked to be new, shape = (n, nx).

        Returns
        -------
        bool
            True if at least one point in Y is not in X, otherwise False."""
        if X.shape[1] != Y.shape[1]:
            raise ValueError("Points must have the same number of dimensions.")
        differences = Y[:, None, :] - X[None, :, :]  # Shape (n, N, nx)
        distances = np.linalg.norm(differences, axis=2)
        if np.max(np.min(distances, axis=0)) > eps:
            return True
        return False

    def save(self, path: str) -> None:
        """Save the predictor to a file.

        Parameters
        ----------
        path : str
            The path to the file."""
        for i in range(self.nr):
            self.classifiers[i].save(i)

    def load(self, path: str) -> None:
        """Load the predictor from a file.

        Parameters
        ----------
        path : str
            The path to the file."""
        for i in range(self.nr):
            self.classifiers[i].load(i)
